name: Run tests on any Push event
on:
  push:
    tags:
      - '!refs/tags/*'
    branches:
      - '*'
jobs:
  test_build:
    runs-on: [ubuntu-latest]
    steps:
      # Чекаутим код
      - uses: actions/checkout@master
      # Устанавливаем python нужной версии
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Initial requrements
        run: pip freeze > requirements.txt
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Add Reporter
        run: pip install coverage
      - name: Run tests
        run: coverage run test-calc.py
      - name: Tests report
        run: coverage report
